---
apiVersion: v1
kind: Namespace
metadata:
  name: sne-userapp2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-svc-deployment #name of deployment
  namespace: sne-userapp2
spec:
  selector: #Tells which pod/pods to manage. Helps to group the pods
    matchLabels:
      app: spring-boot-k8s
  replicas: 4
  template: #template of the pods. Name is same of the selector, so can be selected.
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: user-app-container
          image: 'userapp:2.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9191

---
apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: sne-userapp2
spec:
  selector:
    app: spring-boot-k8s #Same pods' selector name as deployment
  ports:
    - protocol: TCP
      port: 9090 #Port of service, can be anything. Here service accepts the traffice
      targetPort: 9191 #Port where the container will run the application
  type: NodePort
